name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - name: Build With Yarn For Chrome
        run: |
          yarn install
          yarn build
      - name: Build With Yarn For Firefox
        run: |
          yarn install
          yarn build --target=firefox-mv3
      - name: Archive chrome production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generator-extension
          path: build/chrome-mv3-prod
      - name: Archive firefox production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generator-extension
          path: build/firefox-mv3-prod
